name: batch build
on:
  push:
    branches:
      - main
    paths:
      - 'src/batch-a/**'
jobs:
  batch_a_build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/setup-go@v4
      - run: mkdir /go
      - uses: actions/checkout@v3
        with:
          go-version: '^1.20.1'
          path: /go
      - run: go version
      - id: build
        uses: ./.github/actions/build
        with:
          entrypoint: '/go/src/batch-a'
