name: batch build
on:
  push:
    branches:
      - main
    paths:
      - 'src/batch-a/**'
jobs:
  batch_a_build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.1'
      - run: go version
      - id: build
        uses: actions/try_multiple_batches_build@v1
        with:
          entrypoint: 'src/batch-a'
